export const SELLERS_LOADED = "SELLERS_LOADED";
export const SELLERS_LOADING = "SELLERS_LOADING";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
